1st BEGIN: still compiling
2nd BEGIN: still compiling
1st UNITCHECK: done compiling
2nd CHECK: done compiling
1st CHECK: done compiling
1st INIT: started running
2nd INIT: started running
start main running here
main now dying here
3rd END: done running
2nd END: done running
1st END: done running
