(
    A_grave    => "LATIN CAPITAL LETTER A WITH GRAVE",
    A_circ     => "LATIN CAPITAL LETTER A WITH CIRCUMFLEX",
    A_diaer    => "LATIN CAPITAL LETTER A WITH DIAERESIS",
    A_dier     => "LATIN CAPITAL LETTER A WITH DIAERESIS",
    A_uml      => "LATIN CAPITAL LETTER A WITH DIAERESIS",
    A_tilde    => "LATIN CAPITAL LETTER A WITH TILDE",
    A_macron   => "LATIN CAPITAL LETTER A WITH MACRON",
);
