my $answer = 42;                # an integer
my $pi = 3.14159265;            # a "real" number
my $avocados = 6.02e23;         # scientific notation
my $pet = "Camel";              # string
my $sign = "I love my $pet";    # string with interpolation
my $cost = 'It costs $100';     # string without interpolation
my $thence = $whence;           # another variable's value
my $salsa = $moles * $avocados; # a gastrochemical expression
my $exit = system("vi $file");  # numeric status of a command
my $cwd = `pwd`;                # string output from a command
