BINMODE, CLEAR, CLOSE, DELETE, DESTROY, EOF, EXISTS, EXTEND,
FETCH, FETCHSIZE, FILENO, FIRSTKEY, GETC, NEXTKEY, OPEN, POP,
PRINT, PRINTF, PUSH, READ, READLINE, SCALAR, SEEK, SHIFT,
SPLICE, STORE, STORESIZE, TELL, TIEARRAY, TIEHANDLE, TIEHASH,
TIESCALAR, UNSHIFT, and WRITE.
